<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('E-shopping'))->setSeparator(' - ')->setAutoEscape(true); ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.js'))
            ->prependFile($this->basePath('js/jquery.scrollUp.min.js'))
            ->prependFile($this->basePath('js/price-range.js'))
            ->prependFile($this->basePath('js/jquery.prettyPhoto.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <?php echo $this->partial('header');?>
        <?php echo $this->content;?>
        <?php echo $this->inlineScript();?>
    </body>
</html>
